#!/bin/dash
#
# x16-splash — paint the appliance boot splash onto the console framebuffer.
#
# Writes a pre-rendered RGB565 blob straight to /dev/fb0. The image then
# persists as a static picture (no viewer process) until x16emu's KMS modeset
# paints over it.
#
# The blob is picked to match the CURRENT framebuffer, because one image cannot
# serve every target:
#   1920x1080  HDMI default (Pi 3 and Pi 4)
#   1280x720   Pi 3 on a TV that needs the lighter mode (hdmi_mode=4)
#    640x480   Pi 3 + VGA HAT (DPI output, no HDMI connector at all)
#
# Blobs live in /opt/x16 and are generated by tools/gen_splash.py:
#   python3 tools/gen_splash.py --width 1280 --height 720 \
#           --raw x16-splash-1280x720.raw
# All three must be present in the shipped image; a missing one is not an error
# but does mean a black screen instead of a splash on that hardware.
#
# Run early via x16-splash-early.service (firmware framebuffer, ~2.7s), again
# via x16-splash.service after the KMS handover, and once more from custom.sh
# right before launch.
#
# INSTALL: sudo install -m 0755 x16-splash.sh /usr/local/bin/x16-splash
#
FB=/dev/fb0
DIR=/opt/x16

# Wait up to ~12s for a framebuffer to appear.
i=0
while [ ! -e "$FB" ] && [ "$i" -lt 48 ]; do
  i=$((i + 1)); sleep 0.25
done
[ -e "$FB" ] || exit 0

# What is actually on screen right now. Byte count for a full frame is
# stride * yres -- stride, not xres*bpp, because the driver may pad each line.
stride=$(cat /sys/class/graphics/fb0/stride 2>/dev/null || echo 0)
size=$(cat /sys/class/graphics/fb0/virtual_size 2>/dev/null || echo 0,0)
xres=${size%,*}
yres=${size#*,}
want=$(( stride * yres ))
[ "$want" -gt 0 ] || exit 0

# Candidates, most specific first. X16_SPLASH_RAW overrides everything, so a
# one-off panel can be handled without editing this script.
for cand in \
  ${X16_SPLASH_RAW:+"$X16_SPLASH_RAW"} \
  "${DIR}/x16-splash-${xres}x${yres}.raw" \
  "${DIR}/x16-splash.raw"
do
  [ -f "$cand" ] || continue
  have=$(stat -c %s "$cand" 2>/dev/null || echo -1)
  # Size is the only check available, and it is a real one: it catches both the
  # wrong resolution and a truncated file. Drawing a mismatched blob would
  # garble the screen, so skipping is the safe failure.
  [ "$have" -eq "$want" ] || continue
  cat "$cand" > "$FB" 2>/dev/null || true
  exit 0
done

# Nothing matched: leave the screen alone rather than paint garbage.
exit 0
